import { StyleSheet, ViewStyle } from "react-native";

export const theme = {
  colors: {
    backgroundTop: "#FFF6EE",
    backgroundBottom: "#FFD8D7",
    accent: "#F45D6C",
    accentDeep: "#C63A56",
    accentSoft: "#FFE7E5",
    ink: "#231F31",
    muted: "#6C657B",
    card: "rgba(255, 255, 255, 0.84)",
    cardStrong: "rgba(255, 255, 255, 0.95)",
    border: "rgba(255, 255, 255, 0.7)",
    success: "#1F8A70",
    successSoft: "#DBF4EA",
    userBubble: "#231F31",
    matchBubble: "#FFF5F4",
    systemBubble: "#FFF0CF",
  },
  radius: {
    sm: 16,
    md: 22,
    lg: 30,
    pill: 999,
  },
  shadow: {
    shadowColor: "#C63A56",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 8,
  } as ViewStyle,
};

export const styles = StyleSheet.create({
  backgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  screenRoot: {
    flex: 1,
    backgroundColor: theme.colors.backgroundTop,
  },
  safeArea: {
    flex: 1,
  },
  screenContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    gap: 14,
  },
  fixedScreenContent: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
    gap: 14,
  },
  blob: {
    position: "absolute",
    borderRadius: 999,
  },
  blobOne: {
    width: 220,
    height: 220,
    top: -40,
    right: -30,
    backgroundColor: "rgba(244, 93, 108, 0.14)",
  },
  blobTwo: {
    width: 200,
    height: 200,
    bottom: 120,
    left: -80,
    backgroundColor: "rgba(255, 255, 255, 0.42)",
  },
  blobThree: {
    width: 140,
    height: 140,
    bottom: 32,
    right: 24,
    backgroundColor: "rgba(198, 58, 86, 0.1)",
  },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: theme.radius.pill,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  badgeLabel: {
    color: theme.colors.accentDeep,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  hero: {
    gap: 8,
    paddingTop: 4,
  },
  heroTitle: {
    color: theme.colors.ink,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "600",
  },
  heroCopy: {
    color: theme.colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  glassCard: {
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.lg,
    padding: 20,
    ...theme.shadow,
  },
  formCard: {
    gap: 18,
  },
  centeredCard: {
    gap: 16,
    alignItems: "center",
  },
  fieldWrap: {
    gap: 8,
  },
  fieldLabel: {
    color: theme.colors.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  fieldInput: {
    minHeight: 56,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: "rgba(108, 101, 123, 0.14)",
    backgroundColor: theme.colors.cardStrong,
    color: theme.colors.ink,
    fontSize: 15,
    lineHeight: 22,
  },
  fieldHint: {
    color: theme.colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  buttonShell: {
    minWidth: 0,
    borderRadius: theme.radius.pill,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.68)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.7)",
  },
  primaryButtonFill: {
    minHeight: 58,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  primaryButtonLabel: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButtonLabel: {
    minHeight: 58,
    textAlign: "center",
    textAlignVertical: "center",
    color: theme.colors.ink,
    fontSize: 16,
    fontWeight: "700",
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  buttonDisabled: {
    opacity: 0.66,
  },
  buttonPressed: {
    transform: [{ scale: 0.99 }],
  },
  statRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    alignSelf: "stretch",
  },
  statPill: {
    flex: 1,
    minWidth: 120,
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: theme.radius.sm,
    backgroundColor: "rgba(255,255,255,0.8)",
  },
  statLabel: {
    color: theme.colors.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  statValue: {
    color: theme.colors.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  iconWrap: {
    width: 76,
    height: 76,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 38,
    backgroundColor: theme.colors.accentSoft,
  },
  iconText: {
    color: theme.colors.accentDeep,
    fontSize: 34,
    fontWeight: "600",
  },
  popupContent: {
    justifyContent: "center",
  },
  popupTitle: {
    color: theme.colors.ink,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "600",
    textAlign: "center",
  },
  cardTitle: {
    color: theme.colors.ink,
    fontSize: 26,
    textAlign: "center",
    fontWeight: "600",
  },
  cardCopy: {
    color: theme.colors.muted,
    fontSize: 15,
    lineHeight: 23,
    textAlign: "center",
  },
  keyboardView: {
    flex: 1,
  },
  chatScreen: {
    flex: 1,
    minHeight: 0,
  },
  chatHeader: {
    gap: 8,
  },
  chatTitle: {
    color: theme.colors.ink,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "600",
  },
  metaRow: {
    flexDirection: "row",
    gap: 10,
  },
  metaTag: {
    flex: 1,
    minWidth: 0,
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: theme.radius.sm,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  metaLabel: {
    color: theme.colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  metaValue: {
    color: theme.colors.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  summaryCard: {
    gap: 16,
  },
  avatar: {
    width: 62,
    height: 62,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 31,
    backgroundColor: theme.colors.accentSoft,
  },
  revealedAvatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: theme.colors.successSoft,
  },
  avatarText: {
    color: theme.colors.accentDeep,
    fontSize: 28,
    fontWeight: "600",
  },
  revealedAvatarText: {
    color: theme.colors.success,
    fontSize: 38,
  },
  summaryText: {
    gap: 6,
  },
  summaryTitle: {
    color: theme.colors.ink,
    fontSize: 26,
    fontWeight: "600",
  },
  summaryCopy: {
    color: theme.colors.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
  },
  chatCard: {
    flex: 1,
    minHeight: 0,
    gap: 14,
    padding: 16,
    paddingBottom: 12,
    overflow: "hidden",
  },
  chatLabel: {
    color: theme.colors.accentDeep,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  chatScroll: {
    flex: 1,
    minHeight: 0,
  },
  chatContent: {
    flexGrow: 1,
    gap: 12,
    paddingBottom: 12,
  },
  chatRow: {
    alignItems: "flex-start",
  },
  chatRowUser: {
    alignItems: "flex-end",
  },
  chatRowSystem: {
    alignItems: "center",
  },
  chatBubble: {
    maxWidth: "88%",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
  },
  chatBubbleMatch: {
    backgroundColor: theme.colors.matchBubble,
    borderTopLeftRadius: 8,
  },
  chatBubbleUser: {
    backgroundColor: theme.colors.userBubble,
    borderTopRightRadius: 8,
  },
  chatBubbleSystem: {
    backgroundColor: theme.colors.systemBubble,
    borderRadius: theme.radius.sm,
  },
  chatBubbleText: {
    color: theme.colors.ink,
    fontSize: 15,
    lineHeight: 22,
  },
  chatBubbleTextUser: {
    color: "#FFFFFF",
  },
  chatBubbleTextSystem: {
    textAlign: "center",
  },
  composer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.cardStrong,
    borderWidth: 1,
    borderColor: "rgba(108, 101, 123, 0.14)",
  },
  composerInput: {
    flex: 1,
    color: theme.colors.ink,
    fontSize: 15,
    paddingVertical: 2,
  },
  composerSend: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.accentDeep,
  },
  composerSendLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  chatFooter: {
    gap: 10,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
  },
  buttonHalf: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(35, 31, 49, 0.28)",
  },
  modalSheet: {
    margin: 16,
    marginBottom: 24,
    gap: 16,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  modalTitle: {
    color: theme.colors.ink,
    fontSize: 26,
    lineHeight: 32,
    fontWeight: "600",
  },
  modalClose: {
    color: theme.colors.muted,
    fontSize: 14,
    fontWeight: "600",
  },
  modalInput: {
    minHeight: 112,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: "rgba(108, 101, 123, 0.14)",
    backgroundColor: theme.colors.cardStrong,
    color: theme.colors.ink,
    fontSize: 15,
    lineHeight: 22,
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  loadingText: {
    color: theme.colors.muted,
    fontSize: 14,
  },
  answerCard: {
    gap: 8,
    padding: 16,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.accentSoft,
  },
  answerText: {
    color: theme.colors.ink,
    fontSize: 15,
    lineHeight: 23,
  },
});
